source "https://rubygems.org"

ruby "2.5.0"

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

gem "rails", "5.1.5"
gem "jsonapi-serializers", "1.0.0"
gem "jsonapi-realizer", "4.1.0"
